#!/bin/bash
# /etc/init.d/livecar
 
### BEGIN INIT INFO
# Provides: zpc
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: ledblink initscript
# Description: This service is used to manage a led
### END INIT INFO
 
case "$1" in
    start)
        echo "Starting LED Blink"
        /home/pi/script/carclient.sh &
        ;;
    stop)
        echo "Stopping ledblink"
		ps aux|grep twss|awk '{print $2}'|xargs kill -9
		ps aux|grep ffmpeg|awk '{print $2}'|xargs kill -9
        ;;
    *)
        echo "Usage: service ledblink start|stop"
        exit 1
        ;;
esac
exit 0
exit 0
